# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name=b'date bought')),
                ('qtt', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
