# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceCharge', models.IntegerField()),
                ('vat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default=False, upload_to=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'null', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name=b'time ordered')),
                ('category', models.ForeignKey(default=b'null', on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Paid_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'null', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name=b'time paid')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Served_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'null', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name=b'time served')),
                ('is_paid', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=b'null', on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='served_food',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
        migrations.AddField(
            model_name='paid_food',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
        migrations.AddField(
            model_name='ordered_food',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
        migrations.AddField(
            model_name='food',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
    ]
