# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_remove_food_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
    ]
