# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_food_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_food',
            name='title',
        ),
    ]
