# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_remove_paid_food_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_food',
            name='title',
            field=models.CharField(default=b'null', max_length=200),
        ),
    ]
