# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_remove_food_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_food',
            name='qtt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordered_food',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordered_food',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Table'),
        ),
    ]
